---
version: '2'
services:
  presto:
    image: ahanaio/prestodb-sandbox:0.280
    container_name: presto
    volumes:
      - ${PWD}/config/catalog/mongodb.properties:/opt/presto-server/etc/catalog/mongodb.properties
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - presto-nw

  mongodb:
    image: mongo:6.0.4
    container_name: presto-mongo
    volumes:
      - mongoData:/data/db
    ports:
      - "27017:27017"
    networks:
      - presto-nw

networks:
  presto-nw:
    driver: bridge

volumes:
  mongoData: