---
version: '2'
services:
  presto:
    image: ahanaio/prestodb-sandbox:0.280
    container_name: presto
    volumes:
      - ${PWD}/config/catalog/kafka.properties:/opt/presto-server/etc/catalog/kafka.properties
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
    networks:
      - presto-nw

  zookeeper:
    container_name: presto-zookeeper
    image: confluentinc/cp-zookeeper:7.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - presto-nw

  kafka:
    container_name: presto-kafka
    image: confluentinc/cp-kafka:7.2.0
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: presto-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://presto-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
    networks:
      - presto-nw

networks:
  presto-nw:
    driver: bridge

volumes:
  mongoData: